name       = "forclust"
version    = "0.3.0"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2023, Seyed Ali Ghasemi"
[build]
auto-executables = true
auto-tests       = true
auto-examples    = true
[install]
library          = false
[dependencies]
M_CLI2 = {git="https://github.com/urbanjost/M_CLI2.git"}
popen-fortran = {git="https://github.com/jacobwilliams/popen-fortran.git"}